### PR TITLE
Results API

### PR DESCRIPTION
**Pull request by seveibar**

### CODE REVIEW

**Comment by seveibar** [comment]
It's failing b/c travisci doesn't start a rabbitmq instance

**Comment by seveibar** [comment]
...skipping test for now

**Comment by seveibar** [comment]
in the future we should run the `docker-test.yml` of the parent repo, or create a `docker-test.yml` within this directory that is executed in the okcollege-dev context (something like that)

**Comment by seveibar** [comment]
@jowlee

**Review by jowlee — APPROVED** [review]

**Pull request merged**
